---
title: "HW4 mmr starter code"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

Some starter code for HW4, the MMR part. 

```{r}
library(tidyverse)
library(magrittr)
library(tidyverse)
library(dplyr)
library(tidyr)

# source script with functions
# if you are sharing functions with other, writing a (small) package may be preferable 
source("hw4_functions.R")

# read data
mmrdat <- read_rds(gzcon(url("https://people.umass.edu/lalkema/mmr.rds")))
births <- read_rds(gzcon(url("https://people.umass.edu/lalkema/births.rds")))
deaths <- read_rds(gzcon(url("https://people.umass.edu/lalkema/deaths.rds")))
```

```{r}
# # just some tests with mmr_from_pm and pm_from_mmr (not for handing in)
 #mmr_from_pm(0.5, 100, 1000)
# curve(mmr_from_pm(pm = x,deaths =  20*10^5, 
 #                  births = 10^6), xlim = c(0,1)) 
# # check that if you apply both functions, you get the starting point back, here pm
# curve(pm_from_mmr(mmr_from_pm(pm = x, deaths =  20*10^3, births = 10^6), deaths =  20*10^3, births = 10^6), xlim = c(0,1))
# abline(0,1, lty = 2, col = 2)
```

Exercise 1
```{r}
mmrdat <- read_rds(gzcon(url("https://people.umass.edu/lalkema/mmr.rds")))
births <- read_rds(gzcon(url("https://people.umass.edu/lalkema/births.rds")))
deaths <- read_rds(gzcon(url("https://people.umass.edu/lalkema/deaths.rds")))


data_plus <- read_mmrdata(mmrdat, births = births, deaths = deaths) 
```

Exercise 2
```{r}
averagefnc("China", t)
averagefnc("Mozambique", t)
```

Exercise 3
```{r}
plot("Greece", b=NULL, c=NULL)
plot("Brazil", "Spain", "China")
```

Exercise 4
```{r}

# rerun exercise 1:
data_plus <- read_mmrdata(mmrdat, births = births, deaths = deaths)
# rerun exercise 3:
ll <- plotcountry(x, y, z)
```
The End!